### ISSUE TITLE
不好意思打搅，请问framework能不能分享下

### ISSUE THREAD

**Issue by wyk111wyk** [haojinming/RunPythonInIOS#1]

**Comment by haojinming** [comment]
Framwork太大了，github上传不了， 我贴的网址里可以下载到啊

**Comment by ichinaapple** [comment]
你好，能不能知道我一下，我现在没有运行起来代码？一直报错，我的QQ：690563908

**Comment by haojinming** [comment]
具体的失败原因是什么呢？


除了附件中三个framework外还要根据错误提示包含libsqlite3.tbd和libz.tbd


我是根据https://github.com/pybee/Python-Apple-support/tree/2.7里面的提示操作的。






在 2018-03-26 14:57:46，"wei" <notifications@github.com> 写道：


你好，能不能知道我一下，我现在没有运行起来代码？一直是import报错

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

从网易163邮箱发来的云附件
Framework.zip (86.75M, 2018年4月10日 15:20 到期)
下载

**Comment by vio-ez** [comment]
你发的这个链接 https://github.com/pybee/Python-Apple-support ，好像不包含 python.framework，或者是需要另外下载？不太会用，求指点

**Comment by zhuxixing** [comment]
需要的三个框架不知道怎么搞啊？

**Comment by haojinming** [comment]
@MelissaShu 点击Python对应的版本号就可以下载framework

**Comment by haojinming** [comment]
@zhuxixing 上面comment中有指导链接，下载framework，然后添加libsqlite3.tbd和libz.tbd，就可以运行起来了
